version: '3'
services:
  python3.8:
    restart: always
    build: .
    container_name: 'python3.8'
    working_dir: '/root/'
    tty: true
    ports:
    - 8001:8001
    volumes:
      - ./src:/root/src
      - ./notebook:/root/notebook
      - ./data:/root/data